apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: ${{ values.description | dump }}
spec:
  type: workload
  lifecycle: experimental
  owner: ${{ values.developmentGroup | dump }}
  mesh:
    description: ${{ values.description | dump }}
    dependsOn: {% if values.dependsOn | length > 0 %}{% for i in values.dependsOn %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    tags: {% if values.tags | length > 0 %}{% for i in values.tags %}
      - tagFQN: ${{ i }}
        source: Tag
        labelType: Manual
        state: Confirmed{% endfor %}{% else %}[]{% endif %}
    readsFrom: {% if values.readsFrom | length > 0 %}{% for i in values.readsFrom %}
      - ${{ i }}{% endfor %}{% else %}[]{% endif %}
    specific:
      destination:
        namespace: ${{ values.namespace }}
        server: ${{ values.server | dump }}
      source:
        path: ${{ values.path | dump }}
        targetRevision: ${{ values.targetRevision | dump }}
      syncPolicy:
        automated: {% if values.automated %}
          prune: ${{ values.prune | dump }}
          selfHeal: ${{ values.selfHeal | dump }}
        {% else %} null {% endif %}



